# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

max_copula <- function(data, index, n_values, values, log_det, init) {
    .Call(`_maxandsmooth_max_copula`, data, index, n_values, values, log_det, init)
}

max_iid <- function(data, family) {
    .Call(`_maxandsmooth_max_iid`, data, family)
}

